apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deply
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: clown901217/posts
    