apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: ticketing
deploy:
  kubectl:
build:
  local:
    push: false
  artifacts:
    - image: clown901217/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: './'
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/secret.yaml
